---
title: "Welcome"
---


* The course syllabus is stored in the [`Syllabus`](./Syllabus/STT3851Fall2020Syllabus.html) directory of the STT 3851 repository.

* Course pacing and assignments are stored in the [`Assignments`](./Assignments/AssignmentsSTT3851Fall2020.html) directory of the STT 3851 repository.

* [Class RStudio Server](https://mathr.math.appstate.edu) (you must be registered in the course to access the server)

* [Flow Control](./Rmarkdown/FlowControl.html)

* [The Bootstrap](./Rmarkdown/TheBootstrap.html)



## Resources you may find helpful

* [Web site for _The Elements of Statistical Learning_ (free pdf of book)](http://statweb.stanford.edu/~tibs/ElemStatLearn/)

* [Web site for _An Introduction to Statistical Learning_ (free pdf of book)](http://www-bcf.usc.edu/~gareth/ISL/)

* [Course Notes STT 3850 (Spring 2018)](https://alanarnholt.github.io/STT3850/Notes/Parent/Parent.html) 

### Chapter 1: Introduction ([slides](https://courses.edx.org/assets/courseware/v1/af163b1b5874fcb7a86de55dd8205d39/asset-v1:StanfordOnline+STATSX0001+1T2020+type@asset+block/introduction-handout.pdf))

* [Opening Remarks and Examples](https://www.youtube.com/watch?v=5N9V07EIfIg) (18:18)
* [Supervised and Unsupervised Learning](https://www.youtube.com/watch?v=Z0v9QMkA3dA) (12:12)

### Chapter 2: Statistical Learning ([slides](https://courses.edx.org/assets/courseware/v1/389682606dce6fd04aaa833c86e6f577/asset-v1:StanfordOnline+STATSX0001+1T2020+type@asset+block/statistical_learning-handout.pdf))

* [Statistical Learning and Regression](https://www.youtube.com/watch?v=p9n2w236B48) (11:41)
* [Curse of Dimensionality and Parametric Models](https://www.youtube.com/watch?v=HndOzII4jzs) (11:40)
* [Assessing Model Accuracy and Bias-Variance Trade-off](https://www.youtube.com/watch?v=VaN1RUDuioQ) (10:04)
* [Classification Problems and K-Nearest Neighbors](https://www.youtube.com/watch?v=TnVRhLqThR4) (15:37)
* [Lab: Introduction to R](https://www.youtube.com/watch?v=PrIt1t-uCC4) (14:12)

### Chapter 3: Linear Regression ([slides](https://courses.edx.org/assets/courseware/v1/e4f2f4823252ead8c1a68722e3415c28/asset-v1:StanfordOnline+STATSX0001+1T2020+type@asset+block/linear_regression-handout.pdf))

* [Simple Linear Regression and Confidence Intervals](https://www.youtube.com/watch?v=7TgVO_K75EY) (13:01)
* [Hypothesis Testing ](https://www.youtube.com/watch?v=z10DqaVJh3c) (8:24)
* [Multiple Linear Regression and Interpreting Regression Coefficients ](https://www.youtube.com/watch?v=yzQHONabWhs) (15:38)
* [Model Selection and Qualitative Predictors](https://www.youtube.com/watch?v=lo7KnnvyEU0) (14:51)
* [Interactions and Nonlinearity](https://www.youtube.com/watch?v=sK80ZnhiaRI) (14:16)
* [Lab: Linear Regression](https://www.youtube.com/watch?v=W0WILgmAGao) (22:10)

### Chapter 4: Classification ([slides](https://courses.edx.org/assets/courseware/v1/0c7a529a8d32d0449fb5f96d260628ad/asset-v1:StanfordOnline+STATSX0001+1T2020+type@asset+block/classification-handout.pdf))

* [Introduction to Classification](https://www.youtube.com/watch?v=RN_dweQpcpo) (10:25)
* [Logistic Regression and Maximum Likelihood](https://www.youtube.com/watch?v=31Q5FGRnxt4) (9:07)
* [Multivariate Logistic Regression and Confounding](Multivariate Logistic Regression and Confounding) (9:53)
* [Case-Control Sampling and Multiclass Logistic Regression](https://www.youtube.com/watch?v=RIW3H03MNrE) (7:28)
* [Linear Discriminant Analysis and Bayes Theorem](https://www.youtube.com/watch?v=gPOMLCR1oF8) (7:12)
* [Univariate Linear Discriminant Analysis](https://www.youtube.com/watch?v=QG0pVJXT6EU) (7:37)
* [Multivariate Linear Discriminant Analysis and ROC Curves](https://www.youtube.com/watch?v=pZodpSfe9IA) (17:42)
* [Quadratic Discriminant Analysis and Naive Bayes](https://www.youtube.com/watch?v=6FiNGTYAOAA) (10:07)
* [Lab: Logistic Regression](https://www.youtube.com/watch?v=MGertB06qjQ) (10:14)
* [Lab: Linear Discriminant Analysis](https://www.youtube.com/watch?v=2cl7JiPzkBY) (8:22)
* [Lab: K-Nearest Neighbors](https://www.youtube.com/watch?v=OUqMjCfWKiQ) (5:01)

### Chapter 5: Resampling Methods ([slides](https://courses.edx.org/assets/courseware/v1/714c63b497ee6718f12a7fcd24c35866/asset-v1:StanfordOnline+STATSX0001+1T2020+type@asset+block/cv_boot-handout.pdf))

* [Estimating Prediction Error and Validation Set Approach](https://www.youtube.com/watch?v=ngrOYWgJjb4) (14:01)
* [K-fold Cross-Validation](https://www.youtube.com/watch?v=rSGzUy13F_0) (13:33)
* [Cross-Validation: The Right and Wrong Ways](https://www.youtube.com/watch?v=r64tRyHFAJ8) (10:07)
* [The Bootstrap](https://www.youtube.com/watch?v=fBaqG3vpIIg) (11:29)
* [More on the Bootstrap](https://www.youtube.com/watch?v=uX5kPAK0lpo) (14:35)
* [Lab: Cross-Validation](https://www.youtube.com/watch?v=kfl_32v3P_E&t=3s) (11:21)
* [Lab: The Bootstrap](https://www.youtube.com/watch?v=X_UCeAGdAHE) (7:40)

### Chapter 6: Linear Model Selection and Regularization ([slides](https://courses.edx.org/assets/courseware/v1/7eb37b0059a4d1660d163578934a9dcb/asset-v1:StanfordOnline+STATSX0001+1T2020+type@asset+block/model_selection-handout.pdf))

* [Linear Model Selection and Best Subset Selection](https://www.youtube.com/watch?v=XgNub00Uovs) (13:44)
* [Forward Stepwise Selection](https://www.youtube.com/watch?v=3WA-UjeTdQM) (12:26)
* [Backward Stepwise Selection ](https://www.youtube.com/watch?v=JNTe6T26xss) (5:26)
* [Estimating Test Error Using Mallow’s Cp, AIC, BIC, Adjusted R-squared](https://www.youtube.com/watch?v=WWuvcg23O_M) (14:06)
* [Estimating Test Error Using Cross-Validation](https://www.youtube.com/watch?v=f_hkP_We0JY) (8:43)
* [Shrinkage Methods and Ridge Regression](https://www.youtube.com/watch?v=I8bPQ272Pbs) (12:37)
* [The Lasso](https://www.youtube.com/watch?v=FlSQgXv7Dvw) (15:21)
* [Tuning Parameter Selection for Ridge Regression and Lasso](https://www.youtube.com/watch?v=8oEZkHqf_Rk) (5:27)
* [Dimension Reduction](https://www.youtube.com/watch?v=-jgfdSprgnQ) (4:45)
* [Principal Components Regression and Partial Least Squares ](https://www.youtube.com/watch?v=v4lqtr9YZec) (15:48)
* [Lab: Best Subset Selection](https://www.youtube.com/watch?v=MR7rpjN3C6I&t=5s) (10:36)
* [Lab: Forward Stepwise Selection and Model Selection Using Validation Set](https://www.youtube.com/watch?v=2QV3RAOmZ2k) (10:32)
* [Lab: Model Selection Using Cross-Validation](https://www.youtube.com/watch?v=6COMEmQMTLQ) (5:32)
* [Lab: Ridge Regression and Lasso ](https://www.youtube.com/watch?v=ldqJ2sfosqA) (16:34)

### Chapter 7: Moving Beyond Linearity ([slides](https://courses.edx.org/assets/courseware/v1/ca57813d9b515a08f35564427c41b781/asset-v1:StanfordOnline+STATSX0001+1T2020+type@asset+block/nonlinear-handout.pdf))

* [Polynomial Regression and Step Functions ](https://www.youtube.com/watch?v=ItEnKfxKreo) (14:59)
* [Piecewise Polynomials and Splines](https://www.youtube.com/watch?v=s86bsq_EgzU) (13:13)
* [Smoothing Splines](https://www.youtube.com/watch?v=UDDXkffB-aE) (10:10)
* [Local Regression and Generalized Additive Models](https://www.youtube.com/watch?v=h-ExScLnj24) (10:45)
* [Lab: Polynomials](https://www.youtube.com/watch?v=u-rVXhsFyxo) (21:11)
* [Lab: Splines and Generalized Additive Models](https://www.youtube.com/watch?v=Str26mJDDXI) (12:15)

### Chapter 8:  Tree-Based Methods ([slides](https://courses.edx.org/assets/courseware/v1/62c570de505d28b78e8e4ea932daddf2/asset-v1:StanfordOnline+STATSX0001+1T2020+type@asset+block/trees-handout.pdf))

* [Decision Trees](https://www.youtube.com/watch?v=XvdLKUOldkE) (14:37)
* [Pruning a Decision Tree](https://www.youtube.com/watch?v=U9ypJ7UFL3I) (11:45)
* [Classification Trees and Comparison with Linear Models](https://www.youtube.com/watch?v=8foe-MKLgtU) (11:00)
* [Bootstrap Aggregation (Bagging) and Random Forests](https://www.youtube.com/watch?v=omSN-shKM1Y) (13:45)
* [Boosting and Variable Importance](https://www.youtube.com/watch?v=RSWg_islt9c) (12:03)
* [Lab: Decision Trees](https://www.youtube.com/watch?v=YPz2J5lHeVM) (10:13)
* [Lab: Random Forests and Boosting ](https://www.youtube.com/watch?v=MpDEU96Ss8E) (15:35)

### Chapter 9: Support Vector Machines ([slides](https://courses.edx.org/assets/courseware/v1/65d76a3a40298590d15ab2a875e218e2/asset-v1:StanfordOnline+STATSX0001+1T2020+type@asset+block/svm-handout.pdf))

* [Maximal Margin Classifier](https://www.youtube.com/watch?v=m59UOo5jAFU) (11:35)
* [Support Vector Classifier](https://www.youtube.com/watch?v=_TR28WOymkE) (8:04)
* [Kernels and Support Vector Machines](https://www.youtube.com/watch?v=ooYwHNvH-YU) (15:04)
* [Example and Comparison with Logistic Regression](https://www.youtube.com/watch?v=6EFgNdwpB7s) (14:47)
* [Lab: Support Vector Machine for Classification](https://www.youtube.com/watch?v=4KoL9vUI7xs) (10:13)
* [Lab: Nonlinear Support Vector Machine](https://www.youtube.com/watch?v=327P9vMz19Y) (7:54)

### Chapter 10: Unsupervised Learning ([slides](https://courses.edx.org/assets/courseware/v1/fd6af987d74d7a6bbc81668ac47ccda6/asset-v1:StanfordOnline+STATSX0001+1T2020+type@asset+block/unsupervised-handout.pdf))

* [Unsupervised Learning and Principal Components Analysis ](https://www.youtube.com/watch?v=WIMgMBYqhKE) (12:37)
* [Exploring Principal Components Analysis and Proportion of Variance Explained](https://www.youtube.com/watch?v=zMfomUERNww) (17:39)
* [K-means Clustering](https://www.youtube.com/watch?v=6psm_Y5QREU) (17:17)
* [Hierarchical Clustering](https://www.youtube.com/watch?v=7r3jfKKXhjY) (14:45)
* [Breast Cancer Example of Hierarchical Clustering](https://www.youtube.com/watch?v=59TkGcuh5FA) (9:24)
* [Lab: Principal Components Analysis](https://www.youtube.com/watch?v=pOUE0_3aPX8) (6:28)
* [Lab: K-means Clustering](https://www.youtube.com/watch?v=Zp4FJApjOY0) (6:31)
* [Lab: Hierarchical Clustering](https://www.youtube.com/watch?v=-yxzBiesg48 ) (6:33)

### Interviews

* [John Chambers recounts the history of S and R](http://blog.revolutionanalytics.com/2014/01/john-chambers-recounts-the-history-of-s-and-r.html) (10:10)
* [Interview with Bradley Efron](https://www.youtube.com/watch?v=6l9V1sINzhE) (12:08)
* [Interview with Jerome Friedman](https://www.youtube.com/watch?v=79tR7BvYE6w) (10:29)
* [Graduate students](https://www.youtube.com/watch?v=MEMGOlJxxz0) (7:44)

* * *