---
title: "Step AIC"
author: "Alan T. Arnholt"
date: "9/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(MASS)
names(Boston)
cor(Boston)
stepAIC(lm(medv ~ 1, data = Boston), scope = (~crim+zn + indus + chas + nox + rm + age +dis + rad + tax + ptratio + black +lstat), direction = "forward", test = "F")
### OR
null <- lm(medv ~ 1, data = Boston)
full <- lm(medv ~ ., data = Boston)
stepAIC(null, scope = list(lower = null, upper = full), direction = "forward", test = "F")
```
```{r}
mod <- lm(medv ~ lstat + rm + ptratio + dis, data = Boston)
summary(mod)
# 
X <- model.matrix(mod)
XTXI <- solve(t(X)%*%X)
XTXI
# But best to get XTXI using cov.unscaled
XTXI <- summary(mod)$cov.unscaled
XTXI
betahat <- XTXI%*%t(X)%*%Boston$medv
betahat
MSE <- summary(mod)$sigma^2
vcmat <- MSE*XTXI
vcmat
se <- diag(vcmat)^.5
ts <- betahat/se
pvalues <- pt(abs(ts), 501, lower = FALSE)*2
pvalues
CI <- betahat[2] + c(-1, 1)*qt(.975, 501)*se[2]
CI
confint(mod)
```

```{r}
par(mfrow = c(2, 2))
plot(mod)
par(mfrow = c(1,1))
```

```{r}
mod2 <- lm(medv ~ . - age - indus, data = Boston)
summary(mod2)
plot(mod2)
```

```{r}
library(car)
residualPlots(mod)
modM <- lm(medv ~ lstat + rm + ptratio + dis + I(rm^2) + I(lstat^2), data = Boston)
residualPlots(modM)
plot(modM)
summary(modM)
```

```{r}
residualPlots(mod2)
mod3 <- update(mod2, .~. + I(lstat^2) + I(rm^2))
mod3
summary(mod3)
residualPlots(mod3)
```

