---
title: "Assignments STT 3851 - Fall 2019"
author: "Alan T. Arnholt"
date: 'Last Updated on: `r format(Sys.time(), "%b %d, %Y at %X")`'
output: 
  bookdown::html_document2: 
    highlight: textmate
    theme: yeti
    css: "../CSS/style.css"
---

**Aug 19:**

* Go over syllabus.
* Become familiar with the Appstate [RStudio server](https://mathr.math.appstate.edu/). You will use your Appstate user name and password to log in to the server.  You must be registered in the class to access the server.
* Sign-up for free accounts on [GitHub](https://github.com).
* When you register for a free individual GitHub account, request a [student discount](https://education.github.com) to obtain a few private repositories as well as unlimited public repositories.  Please use something similar to **first_name_last_name** as your username when you register with GitHub.  For example, my username on GitHub is *alanarnholt*. If you have a popular name such as John Smith, you may need to provide some other distinquishing characteristic in your **username**.  
* Once you have a GitHub account, send an email to arnholtat@appstate.edu with a Subject line of **STT3851 - GitHub Username**, and tell me in the body of your email your first name, last name, and your GitHub username.

* Homework: 
    + Watch this [video](https://www.youtube.com/watch?v=ZFaWxxzouCY&list=PLjTlxb-wKvXNSDfcKPFH2gzHGyjpeCZmJ&index=3) which provides some background on asking questions.  
    + Read this stackoverflow thread details how to create a [minimal R reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example/5963610#5963610). 
    + Read [How To Ask Questions The Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html) by Eric Raymond and Rick Moen and heed their advice.
    + Read [Getting used to R, RStudio, and R Markdown](https://ismayc.github.io/rbasics-book/)

**Aug 21:**

* In class lecture: Review of one and two sample inference, permutation tests, and bootstrap procedures --- take notes

* [Statistics Review](../Rmarkdown/StatReview.html)
* Link to [Day One Activity and Code](../Rmarkdown/DayOne.html)
* Link to [Day two Activity and Code](../Rmarkdown/day2.html)
    
    ```{block2, note-text, type='rmdnote'}
Most GitHub Classroom assignments due dates are 5 p.m. Friday.
```  

* Homework: Watch the following Videos:
    + [Phillip Guo's Unix-like command line tutorials (Four tutorials about 10 minutes each)](http://www.pgbovine.net/command-line-tutorial.htm)
    + [Phillip Guo's Basic Git and Github tutorials (Three tutorials about 10 minutes each)](http://www.pgbovine.net/git-tutorial.htm)
    + [Clone a GitHub Repo with RStudio (Video)](https://www.youtube.com/watch?v=YxZ8J2rqhEM) (5:05)

**Aug 23:**

* Before class watch the following Videos:
    + [Phillip Guo's Unix-like command line tutorials (Four tutorials about 10 minutes each)](http://www.pgbovine.net/command-line-tutorial.htm)
    + [Phillip Guo's Basic Git and Github tutorials (Three tutorials about 10 minutes each)](http://www.pgbovine.net/git-tutorial.htm)
    + [Clone a GitHub Repo with RStudio (Video)](https://www.youtube.com/watch?v=YxZ8J2rqhEM) (5:05)
* Before class read [Steps for downloading and editing assignments from GitHub Classroom](https://github.com/jfiksel/github-classroom-for-students)
* In class lecture: Review of one and two sample inference, permutation tests, and bootstrap procedures --- take notes
* [Statistics Review](../Rmarkdown/StatReview.html)
* Link to [Day two Activity and Code](../Rmarkdown/day2.html)

* Homework:
    + Read Chapters 1-2 of [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/)
    + Watch [Lab: Introduction to R](https://www.youtube.com/watch?v=jwBgGS_4RQA) (14:12)
    + Reproduce [Modified Introduction to R (Lab1)](https://stat-ata-asu.github.io/ISLR-CHAP2-LAB-SC/Lab1-Solution.html).  Accept assignment from GitHub Classroom---link in ASULEARN. Due Aug 30 

**Aug 26:**

* Before class:
    + Read/review [Getting used to R, RStudio, and R Markdown](https://ismayc.github.io/rbasics-book/)
    + Read the [Git and GitHub](http://r-pkgs.had.co.nz/git.html) chapter from Hadley Wickham's book [R Packages](http://r-pkgs.had.co.nz/)
* Follow the directions from [Happy Git and GitHub for the useR](http://happygitwithr.com/) to [Introduce yourself to Git](http://happygitwithr.com/hello-git.html), [Connect to GitHub](http://happygitwithr.com/push-pull-github.html), and [Cache credentials for HTTPS](http://happygitwithr.com/credential-caching.html).
* Read/review Chapters 1-2 of [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/)


**Aug 28:**

* In class lecture: Review of one and two sample inference, permutation tests, and bootstrap procedures --- take notes
* [Statistics Review](../Rmarkdown/StatReview.html)
* [Schistosomiasis](../Rmarkdown/Schistosomiasis.html)
* Use an avatar or picture on your GitHub account



**Aug 30:**

* Before class:
    + Read chapter 1 [ISLR](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf)
    + Watch [Opening Remarks and Examples](https://www.youtube.com/watch?v=2wLfFB_6SKI) (18:18)
    + Watch [Supervised and Unsupervised Learning](https://www.youtube.com/watch?v=LvaTokhYnDw) (12:12)
    + Read Section 3.4 of [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/)
* Lecture - [Rmarkdown example](../Rmarkdown/FlowControl.html)
* Bootstrap - [Rmarkdown example](../Rmarkdown/TheBootstrap.html)
* [Overplotting Examples and possible Solutions](../Rmarkdown/HousingData.html)

* Due TODAY:
    + Reproduce [Modified Introduction to R (Lab1)](https://stat-ata-asu.github.io/ISLR-CHAP2-LAB-SC/Lab1-Solution.html).  Accept assignment from GitHub Classroom---link in ASULEARN. Due Aug 30 
    
* Homework:
    + Reproduce [Writing Assignment (Lab2)](https://stat-ata-asu.github.io/WritingAssignment-SC/WritingAssignment-Solution.html).  Accept assignment from GitHub Classroom---link in ASULEARN.  Due Sep 6


~~**Sep 2:**~~ **No Class - State Holiday**



**Sep 4:**

* Before class:
    + Read chapter 2 [ISLR](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf)
    + Watch [Statistical Learning and Regression](https://www.youtube.com/watch?v=WjyuiK5taS8) (11:41)
    + Watch [Curse of Dimensionality and Parametric Models](https://www.youtube.com/watch?v=UvxHOkYQl8g) (11:40)
    + Watch [Assessing Model Accuracy and Bias-Variance Trade-off](https://www.youtube.com/watch?v=VusKAosxxyk) (10:04)
* Lecture - Bias Variance Tradeoff - Take notes


**Sep 6:**

* Before class: 
    + Review/read chapter 2 [ISLR](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf)
    + Watch [Classification Problems and K-Nearest Neighbors](https://www.youtube.com/watch?v=vVj2itVNku4) (15:37)
* Lecture - Bias Variance Tradeoff - Take notes - [Slides](../Rmarkdown/BiasVarDer.pdf) 
* Due TODAY:  Reproduce [Writing Assignment (Lab2)](https://stat-ata-asu.github.io/WritingAssignment-SC/WritingAssignment-Solution.html).  Accept assignment from GitHub Classroom---link in ASULEARN.  Due Sep 6


**Sep 9:**

* Before class: 
    + Review/read chapter 2 [ISLR](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf)
* Go over [Bias Variance Graphs](../Rmarkdown/BiasVariance.html) 
* Go over [Chapter 2 Graphs](../Rmarkdown/Chap2Slides.html)
* Discuss flexible models and when to use them
* Homework:
    + [Data Camp Correlation and Regression](https://www.datacamp.com/courses/correlation-and-regression) - Due Sep 13
    + Reproduce [Data Camp Correlation and Regression](https://stat-ata-asu.github.io/CorrelationRegression/) - Accept assignment from GitHub Classroom---link in ASULEARN - Due Sep 20


**Sep 11:**

* Before class:
    + Review [_bookdown: Authoring Books and Technical Documents with R Markdown_](https://bookdown.org/yihui/bookdown/) as needed
* Go over [Bias Variance Graphs](../Rmarkdown/BiasVariance.html) 
* Go over [Chapter 2 Graphs](../Rmarkdown/Chap2Slides.html)


**Sep 13:**

* Work Day
* [Data Camp Correlation and Regression](https://www.datacamp.com/courses/correlation-and-regression) - Due Sep 13
* Reproduce [Data Camp Correlation and Regression (DataCamp1)](https://stat-ata-asu.github.io/CorrelationRegression/) - Accept assignment from GitHub Classroom---link in ASULEARN - Due Sep 20
* [Code](https://raw.githubusercontent.com/alanarnholt/GeneralStatistics/master/rmarkdown/ResidualGraphs.Rmd) to help with the creation of Figure 6.1 in the DataCamp assignment.

**Sep 16:**

* Before class:
    + Read pages 59-82 of [ISLR](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf)
    + Watch [Simple Linear Regression and Confidence Intervals](https://www.youtube.com/watch?v=PsE9UqoWtS4) (13:01)
    + Watch [Hypothesis Testing ](https://www.youtube.com/watch?v=J6AdoiNUyWI) (8:24)
    + Watch [Multiple Linear Regression and Interpreting Regression Coefficients ](https://www.youtube.com/watch?v=1hbCJyM9ccs) (15:38)
* Discuss [Chapter 2 and 3 material](../Rmarkdown/Chap2Slides.html)
* Homework: Reproduce [Data Camp Correlation and Regression (DataCamp1)](https://stat-ata-asu.github.io/CorrelationRegression/) - Accept assignment from GitHub Classroom---link in ASULEARN - Due Sep 20

**Sep 18:**

* Discuss [Chapter 2 and 3 material](../Rmarkdown/Chap2Slides.html)
* Homework: Reproduce [Data Camp Correlation and Regression (DataCamp1)](https://stat-ata-asu.github.io/CorrelationRegression/) - Accept assignment from GitHub Classroom---link in ASULEARN - Due Sep 20

**Sep 20:**

* Workday
* Due TODAY: Reproduce [Data Camp Correlation and Regression (DataCamp1)](https://stat-ata-asu.github.io/CorrelationRegression/) - Accept assignment from GitHub Classroom---link in ASULEARN - Due Sep 20

**Sep 23:**

* Before class:
    + Read pages 82-120 [ISLR](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf)
    + Watch [Model Selection and Qualitative Predictors](https://www.youtube.com/watch?v=3T6RXmIHbJ4) (14:51)
* Discuss [Chapter 2 and 3 material](../Rmarkdown/Chap2Slides.html)
* Go over [Bias Variance Graphs again](../Rmarkdown/BiasVarianceGGplot.html)
* Homework: 
    +  [Data Camp Multiple and Logistic Regression](https://www.datacamp.com/courses/multiple-and-logistic-regression) - Due Sep 27
    +  Reproduce [Data Camp Multiple and Logistic Regression (DataCamp2)](https://stat-ata-asu.github.io/MultipleAndLogisticRegression/) - Accept assignment from GitHub Classroom---link in ASULEARN - Due Oct 4


**Sep 25:**

* Before class:
    + Review pages 82-120 [ISLR](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf)
    + Watch [Interactions and Nonlinearity](https://www.youtube.com/watch?v=IFzVxLv0TKQ) (14:16)
* Discuss [Chapter 2 and 3 material](../Rmarkdown/Chap2Slides.html)
* Homework: 
    +  [Data Camp Multiple and Logistic Regression](https://www.datacamp.com/courses/multiple-and-logistic-regression) - Due Sep 27
    +  Reproduce [Data Camp Multiple and Logistic Regression (DataCamp2)](https://stat-ata-asu.github.io/MultipleAndLogisticRegression/) - Accept assignment from GitHub Classroom---link in ASULEARN - Due Oct 4

**Sep 27:**

* Before class:
    + Review pages 82-120 [ISLR](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf)
    + Watch [Lab: Linear Regression](https://www.youtube.com/watch?v=5ONFqIk3RFg) (22:10)
* Due TODAY: Data Camp Multiple and Logistic Regression - Due Sep 27    
* Homework: 
    + Reproduce [Data Camp Multiple and Logistic Regression (DataCamp2)](https://stat-ata-asu.github.io/MultipleAndLogisticRegression/) - Accept assignment from GitHub Classroom---link in ASULEARN - Due Oct 4   


**Sep 30:**

* Discuss [Chapter 2 and 3 material](../Rmarkdown/Chap2Slides.html)
* Answer questions at the end of [Chapter 2 and 3 material](../Rmarkdown/Chap2Slides.html).
* Homework:
      +  Reproduce [Data Camp Multiple and Logistic Regression (DataCamp2)](https://stat-ata-asu.github.io/MultipleAndLogisticRegression/) - Accept assignment from GitHub Classroom---link in ASULEARN - Due Oct 4
      
**Oct 2:**

* Discuss [Chapter 2 and 3 material](../Rmarkdown/Chap2Slides.html)
* Answer questions at the end of [Chapter 2 and 3 material](../Rmarkdown/Chap2Slides.html).
* Homework:
      +  Reproduce [Data Camp Multiple and Logistic Regression (DataCamp2)](https://stat-ata-asu.github.io/MultipleAndLogisticRegression/) - Accept assignment from GitHub Classroom---link in ASULEARN - Due Oct 4
      +  Complete the take home chapter three assessment (will count as two quizzes) - Accept the assignment from GitHub Classroom --- link in ASULEARN - Due Oct 11

**Oct 4:**

* Due TODAY: Reproduce [Data Camp Multiple and Logistic Regression (DataCamp2)](https://stat-ata-asu.github.io/MultipleAndLogisticRegression/) - Accept assignment from GitHub Classroom---link in ASULEARN - Due Oct 4
* Homework: 
      + Reproduce [Lab: Linear Regression (Lab3)](https://stat-ata-asu.github.io/ISLR-CHAP3-LAB-SC/LabChap3-Solution.html) - Accept assignment from GitHub Classroom---link in ASULEARN - Due Oct 11
      +  Complete the take home chapter three assessment (will count as two quizzes) - Accept the assignment from GitHub Classroom --- link in ASULEARN - Due Oct 11


**Oct 7:**

* Discuss [Chapter 2 and 3 material](../Rmarkdown/Chap2Slides.html)


**Oct 9:**

* Before class:
    + Read the article [_Modeling Home Prices Using Realtor Data_](https://www.tandfonline.com/doi/full/10.1080/10691898.2008.11889569).
    + The data set can be downloaded from http://www.amstat.org/publications/jse/datasets/homes76.dat.txt, while the code book is available from http://www.amstat.org/publications/jse/datasets/homes76.txt
    + Project 1---Accept assignment from GitHub Classroom---link in ASULEARN - Due Oct 25

**Oct 11:**

* Workday
* Due TODAY: 
      + Reproduce [Lab: Linear Regression (Lab3)](https://stat-ata-asu.github.io/ISLR-CHAP3-LAB-SC/LabChap3-Solution.html) - Accept assignment from GitHub Classroom---link in ASULEARN - Due Oct 11
      +  Complete the take home chapter three assessment (will count as two quizzes) - Accept the assignment from GitHub Classroom --- link in ASULEARN - Due Oct 11

~~**Oct 14:**~~ No Class - Fall Break 

**Oct 16:**

* Work on Project 1---Accept assignment from GitHub Classroom---link in ASULEARN - Due Oct 25
* [Code for class notes](../Rmarkdown/BodyTemperatures.html)


**Oct 18:**

* TBD

**Oct 21:**

* TBD


**Oct 23:**

* Before class:
    + Read chapter 5 [ISLR](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf)
    + Watch [Estimating Prediction Error and Validation Set Approach](https://www.youtube.com/watch?v=_2ij6eaaSl0) (14:01)

**Oct 25:**

* Workday
* Due TODAY: Project 1---Accept assignment from GitHub Classroom---link in ASULEARN - Due Oct 25

**Oct 28:**

* Before class:
    + Review chapter 5 [ISLR](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf)
    + Watch [K-fold Cross-Validation](https://www.youtube.com/watch?v=nZAM5OXrktY) (13:33)
    + Watch [Cross-Validation: The Right and Wrong Ways](https://www.youtube.com/watch?v=S06JpVoNaA0) (10:07)

**Oct 30:**

* Before class:
    + Review chapter 5 [ISLR](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf)
    + Watch [Cross-Validation: The Right and Wrong Ways](https://www.youtube.com/watch?v=S06JpVoNaA0) (10:07)

**Nov 1:**

* Before class:
    + Review chapter 5 [ISLR](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf)
    + Watch [Lab: Cross-Validation](https://www.youtube.com/watch?v=6dSXlqHAoMk) (11:21)
* Discuss [Cross-Validation Hand Out](../Rmarkdown/Cross-ValidationInClassHO.html)
* Homework: [Reproduce _Lab: Cross-Validation_ (Lab4)](https://stat-ata-asu.github.io/ISLR-CHAP5-LAB-SC/Lab4-CV.html) --- Accept assignment from GitHub Classroom---link in ASULEARN - Due Nov 8


**Nov 4:**

* Discuss [Cross-Validation Hand Out](../Rmarkdown/Cross-ValidationInClassHO.html)
* Homework: [Reproduce _Lab: Cross-Validation_ (Lab4)](https://stat-ata-asu.github.io/ISLR-CHAP5-LAB-SC/Lab4-CV.html) --- Accept assignment from GitHub Classroom---link in ASULEARN - Due Nov 8

**Nov 6:**

* Discuss [Cross-Validation Hand Out](../Rmarkdown/Cross-ValidationInClassHO.html)
* Homework: [Reproduce _Lab: Cross-Validation_ (Lab4)](https://stat-ata-asu.github.io/ISLR-CHAP5-LAB-SC/Lab4-CV.html) --- Accept assignment from GitHub Classroom---link in ASULEARN - Due Nov 8

**Nov 8:**

* Workday
* Due TODAY: [Reproduce _Lab: Cross-Validation_ (Lab4)](https://stat-ata-asu.github.io/ISLR-CHAP5-LAB-SC/Lab4-CV.html) --- Accept assignment from GitHub Classroom---link in ASULEARN - Due Nov 8
* Homework: [Data Camp Machine Learning Toolbox](https://www.datacamp.com/courses/machine-learning-toolbox) - Due Nov 15 
* Homework: Reproduce [Data Camp Machine Learning Toolbox (DataCamp3)](https://stat-ata-asu.github.io/MachineLearningToolbox/) --- Accept assignment from GitHub Classroom---link in ASULEARN - Due Nov 22 

**Nov 11:**

* TBD

**Nov 13:**

* TBD

**Nov 15:**

* Due TODAY: [Data Camp Machine Learning Toolbox](https://www.datacamp.com/courses/machine-learning-toolbox) - Due Nov 15 

**Nov 18:**

* Before class:
    + Watch [Linear Model Selection and Best Subset Selection](https://www.youtube.com/watch?v=91si52nk3LA) (13:44)
    + [Forward Stepwise Selection](https://www.youtube.com/watch?v=nLpJd_iKmrE) (12:26)
    + [Backward Stepwise Selection ](https://www.youtube.com/watch?v=NJhMSpI2Uj8) (5:26)
    
Start Project 2---InClass Kaggle competition 

* [Example Template Directory](https://github.com/STAT-ATA-ASU/STT3851Spring2016/blob/gh-pages/BDbetaTemplate)
* Use the [housedata.csv](https://github.com/STAT-ATA-ASU/STT3851Spring2016/raw/gh-pages/Data/housedata.csv) file - See [King County Housing Data](../Rmarkdown/KingCounty.html)  
* See ASULEARN for InClass prediction competition link.

**Nov 20:**

* Before class:
    + Watch [Estimating Test Error Using Mallow’s Cp, AIC, BIC, Adjusted R-squared](https://www.youtube.com/watch?v=LkifE44myLc) (14:06)
    + Watch [Estimating Test Error Using Cross-Validation](https://www.youtube.com/watch?v=3p9JNaJCOb4) (8:43)
* [Misc Issues](../Rmarkdown/OneHot.html)
* [Notes on Credit Problem](../Rmarkdown/CreditProblemMore.html)


**Nov 22:**

* Workday
* Due TODAY: Reproduce [Data Camp Machine Learning Toolbox (DataCamp3)](https://stat-ata-asu.github.io/MachineLearningToolbox/) --- Accept assignment from GitHub Classroom---link in ASULEARN - Due Nov 22 
**Nov 25:**

* Before class:
    + Watch [Shrinkage Methods and Ridge Regression](https://www.youtube.com/watch?v=cSKzqb0EKS0) (12:37)
    + Watch [The Lasso](https://www.youtube.com/watch?v=A5I1G1MfUmA) (15:21)
    + Watch [Tuning Parameter Selection for Ridge Regression and Lasso](https://www.youtube.com/watch?v=xMKVUstjXBE) (5:27)

~~**Nov 27-29:**~~ No Class --- State Holiday

**Dec 2:**

* LAST DAY to submit new model for InClass kaggle competition.

* Work on presentation


**Dec 6:**

* Final presentations 2-4:30; WA 307 B





